# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 866aaea44d79bd243f985f061557daa1857aa7e6e38bab8fdee3a3e50aa78bc97630cbe720c982b81bf195df1b1bee9297e84b5f863ce687150b3ff8c37dac7b

test:
  secret_key_base: fb8fa651591281002face5f77a560af71c52a6d26eefcaa50579e6999b3470b6ed8869f710d67293c50a752a6ef154433919ace073ae3ec1d88637944edbc546

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
